server:
  port: 8084
  
spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**,/roles/**
        

      - id: EXPENSE-SERVICE
        uri: lb://EXPENSE-SERVICE
        predicates:
        - Path=/expenses/**
        
      - id: INCOME-SERVICE
        uri: lb://INCOME-SERVICE
        predicates:
        - Path=/incomes/**
        
       
    
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka