server:
  port: 8083
  
spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/income_service_db
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false  